server:
  port: 8088
  servlet:
    context-path: /rt
    path: /api
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    