server:
  port: 8888
  servlet:
    context-path: /rt
spring:
  mvc:
    servlet:
      path: /api  
  datasource:    url: jdbc:mysql://127.0.0.1:3307/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:      min-idle: 5 #最小链接数#
      initial-size: 5 #初始链接数#
      max-total: 20 #最大链接数#
      max-wait-millis: 60000 #超时等待时间#
  jpa:
    show-sql: true
logging:
  level:    org.hibernate.type.descriptor.sql.BasicBinder: trace
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    